### ISSUE TITLE
datasets assert

### ISSUE THREAD

**Issue by HUANGYUEXIN** [MinfengZhu/DM-GAN#1]
I try to run the code, but the path of the datasets is wrong. Can you show me you right path？

**Comment by MinfengZhu** [comment]
Your data directory should be organized like this:

data
│─── birds
│   ├── captions.pickle
│   ├── CUB_200_2011
│   ├── test
│   ├── text
│   └── train
│─── coco
│   ├── captions.pickle
│   ├── images
│   ├── test
│   ├── train
