### ISSUE TITLE
Evaluation on CUB and COCO dataset ?

### ISSUE THREAD

**Issue by di-mi-ta** [MinfengZhu/DM-GAN#11]
Hi author, i have a question that how many epochs you train to obtain IS and FID value with release pretrained model? (800 epochs for CUB and 200 epochs for COCO (in config file) OR  600 epochs for CUB and 120 epochs for COCO (in paper)) ? Many thanks.

**Comment by MinfengZhu** [comment]
The released model was trained with 800 epochs for CUB and 200 epochs for COCO. Then we selected the best model among all epochs.
