### ISSUE TITLE
The sequence of resblock and upblock in NextstageG

### ISSUE THREAD

**Issue by shangshng** [MinfengZhu/DM-GAN#13]
Dear researcher, I have a question about the sequence of resblock and upblock. In your paper the output of Response Gate go firsly to a upblock then towards two resblocks, but in the code it seems go resblocks frist. How is it going? Does the order matters?

**Comment by MinfengZhu** [comment]
It's a mistake in our paper. Two ResBlocks followed by a UpBlock is more efficient during training.

**Comment by hs457681503** [comment]
> Dear researcher, I have a question about the sequence of resblock and upblock. In your paper the output of Response Gate go firsly to a upblock then towards two resblocks, but in the code it seems go resblocks frist. How is it going? Does the order matters?

你好，可以一起学习和交流dmgan吗？我的qq是457681503，盼加，谢谢
