### ISSUE TITLE
Request for release of pretrained discriminator checkpoints

### ISSUE THREAD

**Issue by Amritds** [MinfengZhu/DM-GAN#16]
Hi, 
Would it be possible for you to release the pretrained discriminator checkpoints that correspond to the pretrained DM-GAN generator checkpoints that have been released? I wanted to attempt to fine tune the DM-GAN model (training both discriminators and generators), and it would be much easier to start from the provided pretrained checkpoints than having to re-train from scratch.

**Comment by MinfengZhu** [comment]
The pretrained discriminators have been deleted. Sorry for your inconvenience.
