### ISSUE TITLE
Query regarding spectral.py

### ISSUE THREAD

**Issue by SayanGhoshBDA** [MinfengZhu/DM-GAN#17]
Respected @MinfengZhu and @Basasuya,
1. What is the actual need for forming the class SpectralNorm?
2. Why do we create the additional parameters u and v?
3. Why do we use L2 normalization and what is idea behind updating u,v & w?
4. What is indicated by power_iterations?

**Comment by MinfengZhu** [comment]
Spectral normalization stabilizes the training of the discriminator. Please see https://arxiv.org/pdf/1802.05957.pdf for details. We borrow SN from https://github.com/christiancosgrove/pytorch-spectral-normalization-gan. Power iteration is an iterative method to find the greatest eigenvalue, which is used to regularize the weight matrix.
