### ISSUE TITLE
error when using captions from text file for validation

### ISSUE THREAD

**Issue by tejas-gokhale** [MinfengZhu/DM-GAN#19]
Hi,

I'm trying to load captions from txt files during validation (i.e. the if block on line 223 in datasets.py).
However it gives me the following error:
`RuntimeError: Error(s) in loading state_dict for RNN_ENCODER:
        size mismatch for encoder.weight: copying a param of torch.Size([26835, 300]) from checkpoint, where the shape is torch.Size([27297, 300]) in current model.`

This has also been reported in the AttnGAN issues: https://github.com/taoxugit/AttnGAN/issues/45 
Would be great if you could tell me why this error pops up using txt files.

The validation works if I use the default method.

**Comment by WhereISmyroad** [comment]
> Hi,
> 
> I'm trying to load captions from txt files during validation (i.e. the if block on line 223 in datasets.py).
> However it gives me the following error:
> `RuntimeError: Error(s) in loading state_dict for RNN_ENCODER: size mismatch for encoder.weight: copying a param of torch.Size([26835, 300]) from checkpoint, where the shape is torch.Size([27297, 300]) in current model.`
> 
> This has also been reported in the AttnGAN issues: [taoxugit/AttnGAN#45](https://github.com/taoxugit/AttnGAN/issues/45)
> Would be great if you could tell me why this error pops up using txt files.
> 
> The validation works if I use the default method.

Model mismatch, maybe.
you should train RNN_ENCODER in correct size.

**Comment by MinfengZhu** [comment]
If you want to generate images from customized descriptions, you should modify B_VALIDATION to False.

https://github.com/MinfengZhu/DM-GAN/blob/d515995b6fade48be9762c7f069c9d889d4d5559/code/cfg/eval_bird.yml#L8

**Comment by tejas-gokhale** [comment]
Thanks @WhereISmyroad and @MinfengZhu . Another thing worth mentioning here is that the vocabulary (build_dictionary) of the pre-trained RNN_ENCODER and the new input captions must be the same -- that's the reason for the error. 
Two solutions are 
1. to load the dictionary for the pre-trained model
2. train rnn-encoder with the new dictionary.

Closing the issue. Thanks!
