### ISSUE TITLE
Model Download Links Do Not Exist

### ISSUE THREAD

**Issue by CrazyMoonXD** [MinfengZhu/DM-GAN#7]
DM-GAN for coco or bird don not exist. Furthermore, FID for bird and coco (bird_val.npz and coco_val.npz) also don not find it! Are these web download links wrong? I would appreciate it if you could verify the relevant links.

**Comment by MinfengZhu** [comment]
Sorry for the inconvenience caused. UTS has canceled my google drive, so I upload DM-GAN models and FID files again. You can download these models using new links in README.

**Comment by CrazyMoonXD** [comment]
Thanks a lot.
