### ISSUE TITLE
How do you implement the R precision?Could you share the code?

### ISSUE THREAD

**Issue by imyzx2017** [MinfengZhu/DM-GAN#8]
I tried implementing R precision by myself, but the result I got in attnGAN model, is very low, near 3%.
So how do you implement the R precision?Could you share the code?

Thanks for your help!!

**Comment by imyzx2017** [comment]
sorry, my R precision on attnGAN is near 16.5%.. Still get a low value

**Comment by venuszhou** [comment]
@imyzx2017 so you have implemented the R precision? help wanted.

**Comment by imyzx2017** [comment]
@venuszhou Here is reference for you [https://github.com/imyzx2017/R_Precision_attnGAN](url)

**Comment by MinfengZhu** [comment]
I have updated the code for R-precision.
